TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
